### ISSUE TITLE
Authentication seems to hang (status: 504 Gateway Timeout )

### ISSUE THREAD

**Issue by mrand** [keatontaylor/smartmetertexas-api#1]
I'd love to use this rather than the crazy official API. I loaded the swagger file and attempted to execute it here: 
https://app.swaggerhub.com/apis/mrand/test_smt/1.0.0#/user/post_user_authenticate

which unsurprisingly looks to use curl to test with:

curl -X POST "https://www.smartmetertexas.com/api/user/authenticate" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"username\": \"USER_NAME\", \"password\": \"USER_PASSWORD\", \"rememberMe\": true}"

Is there a work-around or another way to authenticate?  Don't suppose logging in manually and using the cookie would work?

**Comment by xundre** [comment]
Hello, how exactly do you use this? I am intrested in integrating this with home assistant

**Comment by stmrocket** [comment]
I'm not sure, but for Home Assistant, I created a Node-Red flow and HA package to access the API thanks to the notes on this repository.  Cheak out [`ha-smartmetertexas`](https://github.com/stmrocket/ha-smartmetertexas).

**Comment by mrand** [comment]
My [smart_meter_texas repo](https://github.com/mrand/smart_meter_texas) has examples on how to use the official API to do this directly in Home Assistant (without NodeRed).  But the official method is a royal pain, so I'd like to get the unofficial method working and documented as well - I can't get past the authorization step for some reason.  It should be very close to what I have.

@stmrocket, you're saying that it works for you?  I'll have to fire up node red and see if I can understand why.  I added a link to your repo from my README.

**Comment by stmrocket** [comment]
@mrand, I used the notes in the Wiki to create a Node-Red implementation  It doesn't use the actual code located here, but what is in my repo.  I along with another HA user have been testing for several weeks now and it has been working well.

**Comment by xundre** [comment]
Thanks @mrand @stmrocket will try that out

**Comment by mrand** [comment]
@stmrocket THANK YOU!    I figured out the problem... the API is documented as having a "www." prefix, but that doesn't work:

* Connected to www.smartmetertexas.com (23.43.60.138) port 443 (#0)   <<< no response on auth token requests

* Connected to smartmetertexas.com (12.153.148.59) port 443 (#0)  <<< this is what your Node-red flow uses

Follow-up question: do you know how often must re-request tokens?  I don't see it documented here or on your repo.  If no-one knows, I'll experiment

**Comment by stmrocket** [comment]
@mrand Glad you were able to get it working!  Based on observation, the token appears to be good for somewhere around 120 minutes.  Much longer than that and I usually start getting auth errors.
